site_name: Wiki_Data-AI
site_url: https://palomero96.github.io/Wiki_Data-AI/
site_author: Palomero96
site_description: Documentación de Datos&IA
repo_url: https://github.com/Palomero96/Wiki_Data-AI

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - search.suggest
    - search.highlight
    - mathjax
  palette:
      - scheme: slate
        primary: indigo

nav:
  
  - Bases de datos:
    - General: basesdedatos/general.md
    - Cassandra: basesdedatos/cassandra.md
    - MongoDB: basesdedatos/mongodb.md
    - Neo4j: basesdedatos/neo4j.md
    - Redis: basesdedatos/redis.md
  - Datos:
    - Limpieza y transformación: datos/limpiezatransformacion.md
    - Análisis EDA: datos/analisisEDA.md
    - Apache Spark: datos/apachespark.md
    - Kafka, Hive e Impala: datos/kafka_hive_impala.md
  - Estadística:
    - Overview: estadistica/overview.md
    - Probabilidad y distribuciones: estadistica/probabilidad-y-distribuciones.md
    - Regresión y correlación: estadistica/regresion-correlacion.md
    - Análisis multivariante: estadistica/analisis-multivariante.md
    - Inferencia estadística: estadistica/inferencia-estadistica.md
  - Inteligencia Artificial:
    - Overview: inteligenciaartificial/overview.md
    - Aprendizaje Supervisado: inteligenciaartificial/aprendizajesupervisado.md
    - Evaluación Aprendizaje Supervisado: inteligenciaartificial/evaluacionsupervisado.md
    - Aprendizaje No Supervisado: inteligenciaartificial/aprendizajenosupervisado.md
    - Evaluación Aprendizaje No Supervisado: inteligenciaartificial/evaluacionnosupervisado.md
    - Lenguaje natural y Modelos de Lenguaje: inteligenciaartificial/lenguajenaturalymodelos.md
    - Tokens, vectores y embeddings: inteligenciaartificial/tokens_embeddings_vectores_nlp.md
    - Sistema de recomendación: inteligenciaartificial/sistemasrecomendacion.md
    - Otras tecnicas: inteligenciaartificial/otrastecnicas.md

markdown_extensions:
  - admonition
  - codehilite
  - extra
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences

plugins:
  - search


